package com.example.falldetector02.presentation.util.other

const val NOTIFICATION_CHANNEL_ID="falling_channel"
const val NOTIFICATION_CHANNEL_NAME="Falling"
const val NOTIFICATION_ID=1
const val ACTION_START_OR_RESUME_SERVICE="ACTION_START_OR_RESUME_SERVICE"
const val ACTION_PAUSE_SERVICE="ACTION_PAUSE_SERVICE"
const val ACTION_STOP_SERVICE="ACTION_STOP_SERVICE"
const val ACTION_SHOW_DETECTOR="ACTION_SHOW_DETECTOR"

